### PR TITLE
Added Brylie

### PR DESCRIPTION
**Pull request by brylie**

### CODE REVIEW

**Comment by brylie** [comment]
As per: #30

**Comment by Mte90** [comment]
Can you add me as a contributor so we avoid another pull request?

**Comment by brylie** [comment]
OK, how do I do that?

**Comment by Mte90** [comment]
Add this to the readme under your name:
```
* [Mte90](https://github.com/Mte90)
```

**Comment by brylie** [comment]
OK, done.

**Comment by riverspirit** [comment]
Thank you guys :penguin:

**Pull request merged**
