### PR TITLE
Core Fixes (Fonts, mPDF, CSS Separation, CSS Relative path, CSS Injection, Readme)

### PR DESCRIPTION
**Pull request by gabrielmicko**
These core fixes may cause other pull requests expire.

### CODE REVIEW

**Comment by riverspirit** [comment]
Since this is a humongous PR, it is going to take me some time to review and merge this.

Please consider making smaller PRs in the future.

**Comment by gabrielmicko** [comment]
You are right, but In this case I couldn't!

**Comment by gabrielmicko** [comment]
Could you please evaluate this PR?

**Comment by Mte90** [comment]
+1

**Comment by riverspirit** [comment]
Sorry about the delay. I'll get to it as soon as I can.

**Comment by gabrielmicko** [comment]
+1 please

**Comment by Mte90** [comment]
+1

**Comment by riverspirit** [comment]
Sorry for the delay, I've merged the PR. But there is an issue. Images aren't showing up in the generated pdf.

**Comment by gabrielmicko** [comment]
I'll check it soon!

**Comment by gabrielmicko** [comment]
So there is no problem in my development environment. http://mozilla.kreszkviz.hu/Card-Generator/

**Comment by gabrielmicko** [comment]
Sorry for the commit noise. If the images wont show up on your dev environment please set the $GLOBALS['SUBDIR'] = '/Card-Generator'; like this. Replace Card-Generator to your sub folder is necessary.

**Pull request merged**
